<h1 style="text-align:center;font-size:40px;" > Results Summary </h1>

In [2]:
#Ref: http://zetcode.com/python/prettytable/
from prettytable import PrettyTable


x = PrettyTable()
x.field_names = ["Architecture","Test Dice_coeff-Private","Test Dice_coeff-Public"]
x.add_row(["UNET",0.81171,0.80041])
x.add_row(["SEGNET",0.83437,0.84741])
x.add_row(["FCN-8",0.82818,0.84935])
print(x)

+--------------+-------------------------+------------------------+
| Architecture | Test Dice_coeff-Private | Test Dice_coeff-Public |
+--------------+-------------------------+------------------------+
|     UNET     |         0.81171         |        0.80041         |
|    SEGNET    |         0.83437         |        0.84741         |
|    FCN-8     |         0.82818         |        0.84935         |
+--------------+-------------------------+------------------------+


<h1 style="text-align:center;font-size:40px;" > Conclusion </h1>

- Countered the issue of class imbalance by assigning class weights (calculated using SKLearn) during the training stage
- Model training for all architectures was done on resized 128x800 images considering efficiency and computational power
- Model prediction on full sized raw test images (256x1600) gave better scores compared to prediction on half images (128x800)
- Highest score of 0.83437 on private leaderboard & 0.84935 on public leaderboard was obtained with SEGNET & FCN-8 architecture respectively. These scores were better compared to the basic U-NET architecture which was the first cut aproach.

<h1 style="text-align:center;font-size:40px;" > Steps followed to solve this case study(in brief): </h1>

1. The first basic step was to carry out EDA on the defect data. This included analysing images in train & test folder to get a gist of defective & non-defective images, knowing the basic properties of the given images, analysing response label, determining class weights, checking number of labels tagged to each image & observing images with defects belonging to each class.
2. EDA was then followed by Data preparation stage where a master csv file was prepared in which each row represented a image with all possible defects that image possessed.
3. The final data was split into train & CV data in the ratio 85:15 and basic utility functions were defined.
4. Next was the data generator phase where train & validation data was generated in order to feed the keras models with augmented images (in case of train) and ground truth masks.
5. Once the flow of input was set, it was time to implement various segmentation architectures, This included UNET, SEGNET & FCN-8.
6. For each architecture, the performance was checked on the validation image data and few predicted masks were observed.
7. Predictions were made on full sized (i.e 256x1600) raw test images and the predicted masks were observed.
8. Predictions on test images were uploaded on kaggle to get the dice coefficient score